/* 
 * Precisely APIs
 *
 * Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
 *
 * OpenAPI spec version: 11.8.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.precisely.apis.Api;
using com.precisely.apis.Model;
using com.precisely.apis.Client;
using System.Reflection;

namespace com.precisely.apis.Test
{
    /// <summary>
    ///  Class for testing AddressesDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AddressesDTOTests
    {
        // TODO uncomment below to declare an instance variable for AddressesDTO
        //private AddressesDTO instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AddressesDTO
            //instance = new AddressesDTO();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AddressesDTO
        /// </summary>
        [Test]
        public void AddressesDTOInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AddressesDTO
            //Assert.IsInstanceOfType<AddressesDTO> (instance, "variable 'instance' is a AddressesDTO");
        }

        /// <summary>
        /// Test the property 'PbKey'
        /// </summary>
        [Test]
        public void PbKeyTest()
        {
            // TODO unit test for the property 'PbKey'
        }
        /// <summary>
        /// Test the property 'AddressNumber'
        /// </summary>
        [Test]
        public void AddressNumberTest()
        {
            // TODO unit test for the property 'AddressNumber'
        }
        /// <summary>
        /// Test the property 'StreetName'
        /// </summary>
        [Test]
        public void StreetNameTest()
        {
            // TODO unit test for the property 'StreetName'
        }
        /// <summary>
        /// Test the property 'UnitType'
        /// </summary>
        [Test]
        public void UnitTypeTest()
        {
            // TODO unit test for the property 'UnitType'
        }
        /// <summary>
        /// Test the property 'UnitValue'
        /// </summary>
        [Test]
        public void UnitValueTest()
        {
            // TODO unit test for the property 'UnitValue'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'AreaName1'
        /// </summary>
        [Test]
        public void AreaName1Test()
        {
            // TODO unit test for the property 'AreaName1'
        }
        /// <summary>
        /// Test the property 'AreaName2'
        /// </summary>
        [Test]
        public void AreaName2Test()
        {
            // TODO unit test for the property 'AreaName2'
        }
        /// <summary>
        /// Test the property 'AreaName3'
        /// </summary>
        [Test]
        public void AreaName3Test()
        {
            // TODO unit test for the property 'AreaName3'
        }
        /// <summary>
        /// Test the property 'AreaName4'
        /// </summary>
        [Test]
        public void AreaName4Test()
        {
            // TODO unit test for the property 'AreaName4'
        }
        /// <summary>
        /// Test the property 'PostCode'
        /// </summary>
        [Test]
        public void PostCodeTest()
        {
            // TODO unit test for the property 'PostCode'
        }
        /// <summary>
        /// Test the property 'PostCodeExt'
        /// </summary>
        [Test]
        public void PostCodeExtTest()
        {
            // TODO unit test for the property 'PostCodeExt'
        }
        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Test]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }
        /// <summary>
        /// Test the property 'Geometry'
        /// </summary>
        [Test]
        public void GeometryTest()
        {
            // TODO unit test for the property 'Geometry'
        }
        /// <summary>
        /// Test the property 'PropertyType'
        /// </summary>
        [Test]
        public void PropertyTypeTest()
        {
            // TODO unit test for the property 'PropertyType'
        }
        /// <summary>
        /// Test the property 'PropertyTypeDescription'
        /// </summary>
        [Test]
        public void PropertyTypeDescriptionTest()
        {
            // TODO unit test for the property 'PropertyTypeDescription'
        }
        /// <summary>
        /// Test the property 'ParentPbKey'
        /// </summary>
        [Test]
        public void ParentPbKeyTest()
        {
            // TODO unit test for the property 'ParentPbKey'
        }
        /// <summary>
        /// Test the property 'GeoId'
        /// </summary>
        [Test]
        public void GeoIdTest()
        {
            // TODO unit test for the property 'GeoId'
        }

    }

}
