/*
 * Precisely APIs
 *
 * Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
 *
 * The version of the OpenAPI document: 17.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.precisely.apis.Api;
using com.precisely.apis.Model;
using com.precisely.apis.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace com.precisely.apis.Test
{
    /// <summary>
    ///  Class for testing AHJ
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AHJTests
    {
        // TODO uncomment below to declare an instance variable for AHJ
        //private AHJ instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AHJ
            //instance = new AHJ();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AHJ
        /// </summary>
        [Test]
        public void AHJInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" AHJ
            //Assert.IsInstanceOf(typeof(AHJ), instance);
        }


        /// <summary>
        /// Test the property 'AhjType'
        /// </summary>
        [Test]
        public void AhjTypeTest()
        {
            // TODO unit test for the property 'AhjType'
        }
        /// <summary>
        /// Test the property 'AhjId'
        /// </summary>
        [Test]
        public void AhjIdTest()
        {
            // TODO unit test for the property 'AhjId'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'FccId'
        /// </summary>
        [Test]
        public void FccIdTest()
        {
            // TODO unit test for the property 'FccId'
        }
        /// <summary>
        /// Test the property 'Agency'
        /// </summary>
        [Test]
        public void AgencyTest()
        {
            // TODO unit test for the property 'Agency'
        }
        /// <summary>
        /// Test the property 'Phone'
        /// </summary>
        [Test]
        public void PhoneTest()
        {
            // TODO unit test for the property 'Phone'
        }
        /// <summary>
        /// Test the property 'Comments'
        /// </summary>
        [Test]
        public void CommentsTest()
        {
            // TODO unit test for the property 'Comments'
        }
        /// <summary>
        /// Test the property 'Coverage'
        /// </summary>
        [Test]
        public void CoverageTest()
        {
            // TODO unit test for the property 'Coverage'
        }
        /// <summary>
        /// Test the property 'ContactPerson'
        /// </summary>
        [Test]
        public void ContactPersonTest()
        {
            // TODO unit test for the property 'ContactPerson'
        }
        /// <summary>
        /// Test the property 'MailingAddress'
        /// </summary>
        [Test]
        public void MailingAddressTest()
        {
            // TODO unit test for the property 'MailingAddress'
        }

    }

}
