/*
 * Precisely APIs
 *
 * Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
 *
 * The version of the OpenAPI document: 11.9.4
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.precisely.apis.Api;
using com.precisely.apis.Model;
using com.precisely.apis.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace com.precisely.apis.Test
{
    /// <summary>
    ///  Class for testing CandidateRange
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CandidateRangeTests
    {
        // TODO uncomment below to declare an instance variable for CandidateRange
        //private CandidateRange instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CandidateRange
            //instance = new CandidateRange();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CandidateRange
        /// </summary>
        [Test]
        public void CandidateRangeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" CandidateRange
            //Assert.IsInstanceOf(typeof(CandidateRange), instance);
        }


        /// <summary>
        /// Test the property 'PlaceName'
        /// </summary>
        [Test]
        public void PlaceNameTest()
        {
            // TODO unit test for the property 'PlaceName'
        }
        /// <summary>
        /// Test the property 'LowHouse'
        /// </summary>
        [Test]
        public void LowHouseTest()
        {
            // TODO unit test for the property 'LowHouse'
        }
        /// <summary>
        /// Test the property 'HighHouse'
        /// </summary>
        [Test]
        public void HighHouseTest()
        {
            // TODO unit test for the property 'HighHouse'
        }
        /// <summary>
        /// Test the property 'Side'
        /// </summary>
        [Test]
        public void SideTest()
        {
            // TODO unit test for the property 'Side'
        }
        /// <summary>
        /// Test the property 'OddEvenIndicator'
        /// </summary>
        [Test]
        public void OddEvenIndicatorTest()
        {
            // TODO unit test for the property 'OddEvenIndicator'
        }
        /// <summary>
        /// Test the property 'Units'
        /// </summary>
        [Test]
        public void UnitsTest()
        {
            // TODO unit test for the property 'Units'
        }
        /// <summary>
        /// Test the property 'CustomValues'
        /// </summary>
        [Test]
        public void CustomValuesTest()
        {
            // TODO unit test for the property 'CustomValues'
        }

    }

}
