/*
 * Precisely APIs
 *
 * Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
 *
 * The version of the OpenAPI document: 16.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.precisely.apis.Api;
using com.precisely.apis.Model;
using com.precisely.apis.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace com.precisely.apis.Test
{
    /// <summary>
    ///  Class for testing Demographics
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DemographicsTests
    {
        // TODO uncomment below to declare an instance variable for Demographics
        //private Demographics instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Demographics
            //instance = new Demographics();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Demographics
        /// </summary>
        [Test]
        public void DemographicsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" Demographics
            //Assert.IsInstanceOf(typeof(Demographics), instance);
        }


        /// <summary>
        /// Test the property 'Boundaries'
        /// </summary>
        [Test]
        public void BoundariesTest()
        {
            // TODO unit test for the property 'Boundaries'
        }
        /// <summary>
        /// Test the property 'Themes'
        /// </summary>
        [Test]
        public void ThemesTest()
        {
            // TODO unit test for the property 'Themes'
        }
        /// <summary>
        /// Test the property 'BoundaryThemes'
        /// </summary>
        [Test]
        public void BoundaryThemesTest()
        {
            // TODO unit test for the property 'BoundaryThemes'
        }

    }

}
