/*
 * Precisely APIs
 *
 * Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
 *
 * The version of the OpenAPI document: 16.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.precisely.apis.Api;
using com.precisely.apis.Model;
using com.precisely.apis.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace com.precisely.apis.Test
{
    /// <summary>
    ///  Class for testing DemographicsAdvancedPreferences
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DemographicsAdvancedPreferencesTests
    {
        // TODO uncomment below to declare an instance variable for DemographicsAdvancedPreferences
        //private DemographicsAdvancedPreferences instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DemographicsAdvancedPreferences
            //instance = new DemographicsAdvancedPreferences();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DemographicsAdvancedPreferences
        /// </summary>
        [Test]
        public void DemographicsAdvancedPreferencesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" DemographicsAdvancedPreferences
            //Assert.IsInstanceOf(typeof(DemographicsAdvancedPreferences), instance);
        }


        /// <summary>
        /// Test the property 'Profile'
        /// </summary>
        [Test]
        public void ProfileTest()
        {
            // TODO unit test for the property 'Profile'
        }
        /// <summary>
        /// Test the property 'Filter'
        /// </summary>
        [Test]
        public void FilterTest()
        {
            // TODO unit test for the property 'Filter'
        }
        /// <summary>
        /// Test the property 'IncludeGeometry'
        /// </summary>
        [Test]
        public void IncludeGeometryTest()
        {
            // TODO unit test for the property 'IncludeGeometry'
        }

    }

}
