/*
 * Precisely APIs
 *
 * Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
 *
 * The version of the OpenAPI document: 17.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.precisely.apis.Api;
using com.precisely.apis.Model;
using com.precisely.apis.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace com.precisely.apis.Test
{
    /// <summary>
    ///  Class for testing DemographicsThemesV2
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DemographicsThemesV2Tests
    {
        // TODO uncomment below to declare an instance variable for DemographicsThemesV2
        //private DemographicsThemesV2 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DemographicsThemesV2
            //instance = new DemographicsThemesV2();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DemographicsThemesV2
        /// </summary>
        [Test]
        public void DemographicsThemesV2InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" DemographicsThemesV2
            //Assert.IsInstanceOf(typeof(DemographicsThemesV2), instance);
        }


        /// <summary>
        /// Test the property 'BoundaryId'
        /// </summary>
        [Test]
        public void BoundaryIdTest()
        {
            // TODO unit test for the property 'BoundaryId'
        }
        /// <summary>
        /// Test the property 'PopulationTheme'
        /// </summary>
        [Test]
        public void PopulationThemeTest()
        {
            // TODO unit test for the property 'PopulationTheme'
        }
        /// <summary>
        /// Test the property 'RaceAndEthnicityTheme'
        /// </summary>
        [Test]
        public void RaceAndEthnicityThemeTest()
        {
            // TODO unit test for the property 'RaceAndEthnicityTheme'
        }
        /// <summary>
        /// Test the property 'HealthTheme'
        /// </summary>
        [Test]
        public void HealthThemeTest()
        {
            // TODO unit test for the property 'HealthTheme'
        }
        /// <summary>
        /// Test the property 'EducationTheme'
        /// </summary>
        [Test]
        public void EducationThemeTest()
        {
            // TODO unit test for the property 'EducationTheme'
        }
        /// <summary>
        /// Test the property 'IncomeTheme'
        /// </summary>
        [Test]
        public void IncomeThemeTest()
        {
            // TODO unit test for the property 'IncomeTheme'
        }
        /// <summary>
        /// Test the property 'AssetsAndWealthTheme'
        /// </summary>
        [Test]
        public void AssetsAndWealthThemeTest()
        {
            // TODO unit test for the property 'AssetsAndWealthTheme'
        }
        /// <summary>
        /// Test the property 'HouseholdsTheme'
        /// </summary>
        [Test]
        public void HouseholdsThemeTest()
        {
            // TODO unit test for the property 'HouseholdsTheme'
        }
        /// <summary>
        /// Test the property 'HousingTheme'
        /// </summary>
        [Test]
        public void HousingThemeTest()
        {
            // TODO unit test for the property 'HousingTheme'
        }
        /// <summary>
        /// Test the property 'EmploymentTheme'
        /// </summary>
        [Test]
        public void EmploymentThemeTest()
        {
            // TODO unit test for the property 'EmploymentTheme'
        }
        /// <summary>
        /// Test the property 'ExpenditureTheme'
        /// </summary>
        [Test]
        public void ExpenditureThemeTest()
        {
            // TODO unit test for the property 'ExpenditureTheme'
        }
        /// <summary>
        /// Test the property 'SupplyAndDemandTheme'
        /// </summary>
        [Test]
        public void SupplyAndDemandThemeTest()
        {
            // TODO unit test for the property 'SupplyAndDemandTheme'
        }

    }

}
