/*
 * Precisely APIs
 *
 * Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
 *
 * The version of the OpenAPI document: 11.9.3
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.precisely.apis.Api;
using com.precisely.apis.Model;
using com.precisely.apis.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace com.precisely.apis.Test
{
    /// <summary>
    ///  Class for testing EarthquakeRiskByLocationRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EarthquakeRiskByLocationRequestTests
    {
        // TODO uncomment below to declare an instance variable for EarthquakeRiskByLocationRequest
        //private EarthquakeRiskByLocationRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EarthquakeRiskByLocationRequest
            //instance = new EarthquakeRiskByLocationRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EarthquakeRiskByLocationRequest
        /// </summary>
        [Test]
        public void EarthquakeRiskByLocationRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" EarthquakeRiskByLocationRequest
            //Assert.IsInstanceOf(typeof(EarthquakeRiskByLocationRequest), instance);
        }


        /// <summary>
        /// Test the property 'Locations'
        /// </summary>
        [Test]
        public void LocationsTest()
        {
            // TODO unit test for the property 'Locations'
        }
        /// <summary>
        /// Test the property 'Preferences'
        /// </summary>
        [Test]
        public void PreferencesTest()
        {
            // TODO unit test for the property 'Preferences'
        }

    }

}
