/*
 * Precisely APIs
 *
 * Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
 *
 * The version of the OpenAPI document: 17.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.precisely.apis.Api;
using com.precisely.apis.Model;
using com.precisely.apis.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace com.precisely.apis.Test
{
    /// <summary>
    ///  Class for testing FireHistoryV2
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FireHistoryV2Tests
    {
        // TODO uncomment below to declare an instance variable for FireHistoryV2
        //private FireHistoryV2 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FireHistoryV2
            //instance = new FireHistoryV2();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FireHistoryV2
        /// </summary>
        [Test]
        public void FireHistoryV2InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" FireHistoryV2
            //Assert.IsInstanceOf(typeof(FireHistoryV2), instance);
        }


        /// <summary>
        /// Test the property 'StateCode'
        /// </summary>
        [Test]
        public void StateCodeTest()
        {
            // TODO unit test for the property 'StateCode'
        }
        /// <summary>
        /// Test the property 'PostCode'
        /// </summary>
        [Test]
        public void PostCodeTest()
        {
            // TODO unit test for the property 'PostCode'
        }
        /// <summary>
        /// Test the property 'Events'
        /// </summary>
        [Test]
        public void EventsTest()
        {
            // TODO unit test for the property 'Events'
        }

    }

}
