/*
 * Precisely APIs
 *
 * Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
 *
 * The version of the OpenAPI document: 11.9.3
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.precisely.apis.Api;
using com.precisely.apis.Model;
using com.precisely.apis.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace com.precisely.apis.Test
{
    /// <summary>
    ///  Class for testing GeoLocationIpAddr
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GeoLocationIpAddrTests
    {
        // TODO uncomment below to declare an instance variable for GeoLocationIpAddr
        //private GeoLocationIpAddr instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GeoLocationIpAddr
            //instance = new GeoLocationIpAddr();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GeoLocationIpAddr
        /// </summary>
        [Test]
        public void GeoLocationIpAddrInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" GeoLocationIpAddr
            //Assert.IsInstanceOf(typeof(GeoLocationIpAddr), instance);
        }


        /// <summary>
        /// Test the property 'Geometry'
        /// </summary>
        [Test]
        public void GeometryTest()
        {
            // TODO unit test for the property 'Geometry'
        }
        /// <summary>
        /// Test the property 'Accuracy'
        /// </summary>
        [Test]
        public void AccuracyTest()
        {
            // TODO unit test for the property 'Accuracy'
        }
        /// <summary>
        /// Test the property 'IpInfo'
        /// </summary>
        [Test]
        public void IpInfoTest()
        {
            // TODO unit test for the property 'IpInfo'
        }

    }

}
