/*
 * Precisely APIs
 *
 * Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
 *
 * The version of the OpenAPI document: 14.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.precisely.apis.Api;
using com.precisely.apis.Model;
using com.precisely.apis.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace com.precisely.apis.Test
{
    /// <summary>
    ///  Class for testing GetPostalCodesAPIInputRow
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetPostalCodesAPIInputRowTests
    {
        // TODO uncomment below to declare an instance variable for GetPostalCodesAPIInputRow
        //private GetPostalCodesAPIInputRow instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GetPostalCodesAPIInputRow
            //instance = new GetPostalCodesAPIInputRow();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GetPostalCodesAPIInputRow
        /// </summary>
        [Test]
        public void GetPostalCodesAPIInputRowInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" GetPostalCodesAPIInputRow
            //Assert.IsInstanceOf(typeof(GetPostalCodesAPIInputRow), instance);
        }


        /// <summary>
        /// Test the property 'UserFields'
        /// </summary>
        [Test]
        public void UserFieldsTest()
        {
            // TODO unit test for the property 'UserFields'
        }
        /// <summary>
        /// Test the property 'City'
        /// </summary>
        [Test]
        public void CityTest()
        {
            // TODO unit test for the property 'City'
        }
        /// <summary>
        /// Test the property 'StateProvince'
        /// </summary>
        [Test]
        public void StateProvinceTest()
        {
            // TODO unit test for the property 'StateProvince'
        }

    }

}
