/*
 * Precisely APIs
 *
 * Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
 *
 * The version of the OpenAPI document: 18.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.precisely.apis.Api;
using com.precisely.apis.Model;
using com.precisely.apis.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace com.precisely.apis.Test
{
    /// <summary>
    ///  Class for testing Greatschools
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GreatschoolsTests
    {
        // TODO uncomment below to declare an instance variable for Greatschools
        //private Greatschools instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Greatschools
            //instance = new Greatschools();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Greatschools
        /// </summary>
        [Test]
        public void GreatschoolsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" Greatschools
            //Assert.IsInstanceOf(typeof(Greatschools), instance);
        }


        /// <summary>
        /// Test the property 'GsId'
        /// </summary>
        [Test]
        public void GsIdTest()
        {
            // TODO unit test for the property 'GsId'
        }
        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Test]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
        /// <summary>
        /// Test the property 'Rating'
        /// </summary>
        [Test]
        public void RatingTest()
        {
            // TODO unit test for the property 'Rating'
        }

    }

}
