/*
 * Precisely APIs
 *
 * Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
 *
 * The version of the OpenAPI document: 18.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.precisely.apis.Api;
using com.precisely.apis.Model;
using com.precisely.apis.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace com.precisely.apis.Test
{
    /// <summary>
    ///  Class for testing Name
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NameTests
    {
        // TODO uncomment below to declare an instance variable for Name
        //private Name instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Name
            //instance = new Name();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Name
        /// </summary>
        [Test]
        public void NameInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" Name
            //Assert.IsInstanceOf(typeof(Name), instance);
        }


        /// <summary>
        /// Test the property 'LangISOCode'
        /// </summary>
        [Test]
        public void LangISOCodeTest()
        {
            // TODO unit test for the property 'LangISOCode'
        }
        /// <summary>
        /// Test the property 'LangType'
        /// </summary>
        [Test]
        public void LangTypeTest()
        {
            // TODO unit test for the property 'LangType'
        }
        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Test]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }

    }

}
