/*
 * Precisely APIs
 *
 * Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
 *
 * The version of the OpenAPI document: 17.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.precisely.apis.Api;
using com.precisely.apis.Model;
using com.precisely.apis.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace com.precisely.apis.Test
{
    /// <summary>
    ///  Class for testing PoiCountRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PoiCountRequestTests
    {
        // TODO uncomment below to declare an instance variable for PoiCountRequest
        //private PoiCountRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PoiCountRequest
            //instance = new PoiCountRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PoiCountRequest
        /// </summary>
        [Test]
        public void PoiCountRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" PoiCountRequest
            //Assert.IsInstanceOf(typeof(PoiCountRequest), instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'CategoryCode'
        /// </summary>
        [Test]
        public void CategoryCodeTest()
        {
            // TODO unit test for the property 'CategoryCode'
        }
        /// <summary>
        /// Test the property 'SicCode'
        /// </summary>
        [Test]
        public void SicCodeTest()
        {
            // TODO unit test for the property 'SicCode'
        }
        /// <summary>
        /// Test the property 'FuzzyOnName'
        /// </summary>
        [Test]
        public void FuzzyOnNameTest()
        {
            // TODO unit test for the property 'FuzzyOnName'
        }
        /// <summary>
        /// Test the property 'MatchMode'
        /// </summary>
        [Test]
        public void MatchModeTest()
        {
            // TODO unit test for the property 'MatchMode'
        }
        /// <summary>
        /// Test the property 'SpecificMatchOn'
        /// </summary>
        [Test]
        public void SpecificMatchOnTest()
        {
            // TODO unit test for the property 'SpecificMatchOn'
        }
        /// <summary>
        /// Test the property 'Geometry'
        /// </summary>
        [Test]
        public void GeometryTest()
        {
            // TODO unit test for the property 'Geometry'
        }
        /// <summary>
        /// Test the property 'GeometryAsText'
        /// </summary>
        [Test]
        public void GeometryAsTextTest()
        {
            // TODO unit test for the property 'GeometryAsText'
        }

    }

}
