/* 
 * Precisely APIs
 *
 * Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
 *
 * OpenAPI spec version: 11.6.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.precisely.apis.Api;
using com.precisely.apis.Model;
using com.precisely.apis.Client;
using System.Reflection;

namespace com.precisely.apis.Test
{
    /// <summary>
    ///  Class for testing PropertyAttributes
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PropertyAttributesTests
    {
        // TODO uncomment below to declare an instance variable for PropertyAttributes
        //private PropertyAttributes instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PropertyAttributes
            //instance = new PropertyAttributes();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PropertyAttributes
        /// </summary>
        [Test]
        public void PropertyAttributesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PropertyAttributes
            //Assert.IsInstanceOfType<PropertyAttributes> (instance, "variable 'instance' is a PropertyAttributes");
        }

        /// <summary>
        /// Test the property 'PbKey'
        /// </summary>
        [Test]
        public void PbKeyTest()
        {
            // TODO unit test for the property 'PbKey'
        }
        /// <summary>
        /// Test the property 'PropApn'
        /// </summary>
        [Test]
        public void PropApnTest()
        {
            // TODO unit test for the property 'PropApn'
        }
        /// <summary>
        /// Test the property 'PropType'
        /// </summary>
        [Test]
        public void PropTypeTest()
        {
            // TODO unit test for the property 'PropType'
        }
        /// <summary>
        /// Test the property 'PropSqFt'
        /// </summary>
        [Test]
        public void PropSqFtTest()
        {
            // TODO unit test for the property 'PropSqFt'
        }
        /// <summary>
        /// Test the property 'BuildgSqFt'
        /// </summary>
        [Test]
        public void BuildgSqFtTest()
        {
            // TODO unit test for the property 'BuildgSqFt'
        }
        /// <summary>
        /// Test the property 'BuildgSqSource'
        /// </summary>
        [Test]
        public void BuildgSqSourceTest()
        {
            // TODO unit test for the property 'BuildgSqSource'
        }
        /// <summary>
        /// Test the property 'LandUse'
        /// </summary>
        [Test]
        public void LandUseTest()
        {
            // TODO unit test for the property 'LandUse'
        }
        /// <summary>
        /// Test the property 'Construction'
        /// </summary>
        [Test]
        public void ConstructionTest()
        {
            // TODO unit test for the property 'Construction'
        }
        /// <summary>
        /// Test the property 'RoofType'
        /// </summary>
        [Test]
        public void RoofTypeTest()
        {
            // TODO unit test for the property 'RoofType'
        }
        /// <summary>
        /// Test the property 'Subdivision'
        /// </summary>
        [Test]
        public void SubdivisionTest()
        {
            // TODO unit test for the property 'Subdivision'
        }
        /// <summary>
        /// Test the property 'Geometry'
        /// </summary>
        [Test]
        public void GeometryTest()
        {
            // TODO unit test for the property 'Geometry'
        }
        /// <summary>
        /// Test the property 'BuiltYear'
        /// </summary>
        [Test]
        public void BuiltYearTest()
        {
            // TODO unit test for the property 'BuiltYear'
        }
        /// <summary>
        /// Test the property 'Bedrooms'
        /// </summary>
        [Test]
        public void BedroomsTest()
        {
            // TODO unit test for the property 'Bedrooms'
        }
        /// <summary>
        /// Test the property 'Baths'
        /// </summary>
        [Test]
        public void BathsTest()
        {
            // TODO unit test for the property 'Baths'
        }
        /// <summary>
        /// Test the property 'Pool'
        /// </summary>
        [Test]
        public void PoolTest()
        {
            // TODO unit test for the property 'Pool'
        }
        /// <summary>
        /// Test the property 'FirePlace'
        /// </summary>
        [Test]
        public void FirePlaceTest()
        {
            // TODO unit test for the property 'FirePlace'
        }
        /// <summary>
        /// Test the property 'MobileHome'
        /// </summary>
        [Test]
        public void MobileHomeTest()
        {
            // TODO unit test for the property 'MobileHome'
        }
        /// <summary>
        /// Test the property 'HeatingType'
        /// </summary>
        [Test]
        public void HeatingTypeTest()
        {
            // TODO unit test for the property 'HeatingType'
        }
        /// <summary>
        /// Test the property 'CoolingType'
        /// </summary>
        [Test]
        public void CoolingTypeTest()
        {
            // TODO unit test for the property 'CoolingType'
        }
        /// <summary>
        /// Test the property 'AssessedValue'
        /// </summary>
        [Test]
        public void AssessedValueTest()
        {
            // TODO unit test for the property 'AssessedValue'
        }
        /// <summary>
        /// Test the property 'MarketValue'
        /// </summary>
        [Test]
        public void MarketValueTest()
        {
            // TODO unit test for the property 'MarketValue'
        }
        /// <summary>
        /// Test the property 'AppraisedValue'
        /// </summary>
        [Test]
        public void AppraisedValueTest()
        {
            // TODO unit test for the property 'AppraisedValue'
        }
        /// <summary>
        /// Test the property 'TaxAmount'
        /// </summary>
        [Test]
        public void TaxAmountTest()
        {
            // TODO unit test for the property 'TaxAmount'
        }
        /// <summary>
        /// Test the property 'TaxExemptions'
        /// </summary>
        [Test]
        public void TaxExemptionsTest()
        {
            // TODO unit test for the property 'TaxExemptions'
        }
        /// <summary>
        /// Test the property 'CaExemptions'
        /// </summary>
        [Test]
        public void CaExemptionsTest()
        {
            // TODO unit test for the property 'CaExemptions'
        }
        /// <summary>
        /// Test the property 'Stories'
        /// </summary>
        [Test]
        public void StoriesTest()
        {
            // TODO unit test for the property 'Stories'
        }
        /// <summary>
        /// Test the property 'SalesDate'
        /// </summary>
        [Test]
        public void SalesDateTest()
        {
            // TODO unit test for the property 'SalesDate'
        }
        /// <summary>
        /// Test the property 'PriorSaleDate'
        /// </summary>
        [Test]
        public void PriorSaleDateTest()
        {
            // TODO unit test for the property 'PriorSaleDate'
        }
        /// <summary>
        /// Test the property 'PriorSalesPrice'
        /// </summary>
        [Test]
        public void PriorSalesPriceTest()
        {
            // TODO unit test for the property 'PriorSalesPrice'
        }
        /// <summary>
        /// Test the property 'LivingSqft'
        /// </summary>
        [Test]
        public void LivingSqftTest()
        {
            // TODO unit test for the property 'LivingSqft'
        }
        /// <summary>
        /// Test the property 'RoofFrameType'
        /// </summary>
        [Test]
        public void RoofFrameTypeTest()
        {
            // TODO unit test for the property 'RoofFrameType'
        }
        /// <summary>
        /// Test the property 'Foundation'
        /// </summary>
        [Test]
        public void FoundationTest()
        {
            // TODO unit test for the property 'Foundation'
        }
        /// <summary>
        /// Test the property 'BuildgCondition'
        /// </summary>
        [Test]
        public void BuildgConditionTest()
        {
            // TODO unit test for the property 'BuildgCondition'
        }
        /// <summary>
        /// Test the property 'BuildgCount'
        /// </summary>
        [Test]
        public void BuildgCountTest()
        {
            // TODO unit test for the property 'BuildgCount'
        }
        /// <summary>
        /// Test the property 'BuildgUnitNo'
        /// </summary>
        [Test]
        public void BuildgUnitNoTest()
        {
            // TODO unit test for the property 'BuildgUnitNo'
        }
        /// <summary>
        /// Test the property 'BuildgFeaturesSqft'
        /// </summary>
        [Test]
        public void BuildgFeaturesSqftTest()
        {
            // TODO unit test for the property 'BuildgFeaturesSqft'
        }

    }

}
