/*
 * Precisely APIs
 *
 * Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
 *
 * The version of the OpenAPI document: 16.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.precisely.apis.Api;
using com.precisely.apis.Model;
using com.precisely.apis.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace com.precisely.apis.Test
{
    /// <summary>
    ///  Class for testing PropertyInfoResponses
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PropertyInfoResponsesTests
    {
        // TODO uncomment below to declare an instance variable for PropertyInfoResponses
        //private PropertyInfoResponses instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PropertyInfoResponses
            //instance = new PropertyInfoResponses();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PropertyInfoResponses
        /// </summary>
        [Test]
        public void PropertyInfoResponsesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" PropertyInfoResponses
            //Assert.IsInstanceOf(typeof(PropertyInfoResponses), instance);
        }


        /// <summary>
        /// Test the property '_PropertyInfoResponses'
        /// </summary>
        [Test]
        public void _PropertyInfoResponsesTest()
        {
            // TODO unit test for the property '_PropertyInfoResponses'
        }

    }

}
