/*
 * Precisely APIs
 *
 * Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
 *
 * The version of the OpenAPI document: 12.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.precisely.apis.Api;
using com.precisely.apis.Model;
using com.precisely.apis.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace com.precisely.apis.Test
{
    /// <summary>
    ///  Class for testing PSAPResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PSAPResponseTests
    {
        // TODO uncomment below to declare an instance variable for PSAPResponse
        //private PSAPResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PSAPResponse
            //instance = new PSAPResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PSAPResponse
        /// </summary>
        [Test]
        public void PSAPResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" PSAPResponse
            //Assert.IsInstanceOf(typeof(PSAPResponse), instance);
        }


        /// <summary>
        /// Test the property 'PsapId'
        /// </summary>
        [Test]
        public void PsapIdTest()
        {
            // TODO unit test for the property 'PsapId'
        }
        /// <summary>
        /// Test the property 'FccId'
        /// </summary>
        [Test]
        public void FccIdTest()
        {
            // TODO unit test for the property 'FccId'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Count'
        /// </summary>
        [Test]
        public void CountTest()
        {
            // TODO unit test for the property 'Count'
        }
        /// <summary>
        /// Test the property 'Agency'
        /// </summary>
        [Test]
        public void AgencyTest()
        {
            // TODO unit test for the property 'Agency'
        }
        /// <summary>
        /// Test the property 'Phone'
        /// </summary>
        [Test]
        public void PhoneTest()
        {
            // TODO unit test for the property 'Phone'
        }
        /// <summary>
        /// Test the property 'County'
        /// </summary>
        [Test]
        public void CountyTest()
        {
            // TODO unit test for the property 'County'
        }
        /// <summary>
        /// Test the property 'Coverage'
        /// </summary>
        [Test]
        public void CoverageTest()
        {
            // TODO unit test for the property 'Coverage'
        }
        /// <summary>
        /// Test the property 'ContactPerson'
        /// </summary>
        [Test]
        public void ContactPersonTest()
        {
            // TODO unit test for the property 'ContactPerson'
        }
        /// <summary>
        /// Test the property 'SiteDetails'
        /// </summary>
        [Test]
        public void SiteDetailsTest()
        {
            // TODO unit test for the property 'SiteDetails'
        }
        /// <summary>
        /// Test the property 'MailingAddress'
        /// </summary>
        [Test]
        public void MailingAddressTest()
        {
            // TODO unit test for the property 'MailingAddress'
        }

    }

}
