/*
 * Precisely APIs
 *
 * Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
 *
 * The version of the OpenAPI document: 16.0.1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.precisely.apis.Api;
using com.precisely.apis.Model;
using com.precisely.apis.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace com.precisely.apis.Test
{
    /// <summary>
    ///  Class for testing Risk
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RiskTests
    {
        // TODO uncomment below to declare an instance variable for Risk
        //private Risk instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Risk
            //instance = new Risk();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Risk
        /// </summary>
        [Test]
        public void RiskInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" Risk
            //Assert.IsInstanceOf(typeof(Risk), instance);
        }


        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Risk50Rating'
        /// </summary>
        [Test]
        public void Risk50RatingTest()
        {
            // TODO unit test for the property 'Risk50Rating'
        }
        /// <summary>
        /// Test the property 'Frequency'
        /// </summary>
        [Test]
        public void FrequencyTest()
        {
            // TODO unit test for the property 'Frequency'
        }
        /// <summary>
        /// Test the property 'Nonburn'
        /// </summary>
        [Test]
        public void NonburnTest()
        {
            // TODO unit test for the property 'Nonburn'
        }
        /// <summary>
        /// Test the property 'PastFires'
        /// </summary>
        [Test]
        public void PastFiresTest()
        {
            // TODO unit test for the property 'PastFires'
        }
        /// <summary>
        /// Test the property 'Severity'
        /// </summary>
        [Test]
        public void SeverityTest()
        {
            // TODO unit test for the property 'Severity'
        }
        /// <summary>
        /// Test the property 'Continuity'
        /// </summary>
        [Test]
        public void ContinuityTest()
        {
            // TODO unit test for the property 'Continuity'
        }
        /// <summary>
        /// Test the property 'Adjustment'
        /// </summary>
        [Test]
        public void AdjustmentTest()
        {
            // TODO unit test for the property 'Adjustment'
        }
        /// <summary>
        /// Test the property 'Aspect'
        /// </summary>
        [Test]
        public void AspectTest()
        {
            // TODO unit test for the property 'Aspect'
        }
        /// <summary>
        /// Test the property 'CrownFire'
        /// </summary>
        [Test]
        public void CrownFireTest()
        {
            // TODO unit test for the property 'CrownFire'
        }
        /// <summary>
        /// Test the property 'Vegetation'
        /// </summary>
        [Test]
        public void VegetationTest()
        {
            // TODO unit test for the property 'Vegetation'
        }
        /// <summary>
        /// Test the property 'Foehn'
        /// </summary>
        [Test]
        public void FoehnTest()
        {
            // TODO unit test for the property 'Foehn'
        }
        /// <summary>
        /// Test the property 'GolfCourse'
        /// </summary>
        [Test]
        public void GolfCourseTest()
        {
            // TODO unit test for the property 'GolfCourse'
        }
        /// <summary>
        /// Test the property 'RoadDist'
        /// </summary>
        [Test]
        public void RoadDistTest()
        {
            // TODO unit test for the property 'RoadDist'
        }
        /// <summary>
        /// Test the property 'Slope'
        /// </summary>
        [Test]
        public void SlopeTest()
        {
            // TODO unit test for the property 'Slope'
        }
        /// <summary>
        /// Test the property 'WaterDist'
        /// </summary>
        [Test]
        public void WaterDistTest()
        {
            // TODO unit test for the property 'WaterDist'
        }
        /// <summary>
        /// Test the property 'Tier'
        /// </summary>
        [Test]
        public void TierTest()
        {
            // TODO unit test for the property 'Tier'
        }
        /// <summary>
        /// Test the property 'TierDescription'
        /// </summary>
        [Test]
        public void TierDescriptionTest()
        {
            // TODO unit test for the property 'TierDescription'
        }
        /// <summary>
        /// Test the property 'DistanceToFireStation'
        /// </summary>
        [Test]
        public void DistanceToFireStationTest()
        {
            // TODO unit test for the property 'DistanceToFireStation'
        }

    }

}
