/*
 * Precisely APIs
 *
 * Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
 *
 * The version of the OpenAPI document: 16.0.1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.precisely.apis.Api;
using com.precisely.apis.Model;
using com.precisely.apis.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace com.precisely.apis.Test
{
    /// <summary>
    ///  Class for testing RouteResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RouteResponseTests
    {
        // TODO uncomment below to declare an instance variable for RouteResponse
        //private RouteResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RouteResponse
            //instance = new RouteResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RouteResponse
        /// </summary>
        [Test]
        public void RouteResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" RouteResponse
            //Assert.IsInstanceOf(typeof(RouteResponse), instance);
        }


        /// <summary>
        /// Test the property 'DirectionsStyle'
        /// </summary>
        [Test]
        public void DirectionsStyleTest()
        {
            // TODO unit test for the property 'DirectionsStyle'
        }
        /// <summary>
        /// Test the property 'Distance'
        /// </summary>
        [Test]
        public void DistanceTest()
        {
            // TODO unit test for the property 'Distance'
        }
        /// <summary>
        /// Test the property 'DistanceUnit'
        /// </summary>
        [Test]
        public void DistanceUnitTest()
        {
            // TODO unit test for the property 'DistanceUnit'
        }
        /// <summary>
        /// Test the property 'Language'
        /// </summary>
        [Test]
        public void LanguageTest()
        {
            // TODO unit test for the property 'Language'
        }
        /// <summary>
        /// Test the property 'TimeUnit'
        /// </summary>
        [Test]
        public void TimeUnitTest()
        {
            // TODO unit test for the property 'TimeUnit'
        }
        /// <summary>
        /// Test the property 'Time'
        /// </summary>
        [Test]
        public void TimeTest()
        {
            // TODO unit test for the property 'Time'
        }
        /// <summary>
        /// Test the property 'Geometry'
        /// </summary>
        [Test]
        public void GeometryTest()
        {
            // TODO unit test for the property 'Geometry'
        }
        /// <summary>
        /// Test the property 'RouteDirections'
        /// </summary>
        [Test]
        public void RouteDirectionsTest()
        {
            // TODO unit test for the property 'RouteDirections'
        }
        /// <summary>
        /// Test the property 'IntermediatePoints'
        /// </summary>
        [Test]
        public void IntermediatePointsTest()
        {
            // TODO unit test for the property 'IntermediatePoints'
        }

    }

}
