/*
 * Precisely APIs
 *
 * Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
 *
 * The version of the OpenAPI document: 11.9.2
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.precisely.apis.Api;
using com.precisely.apis.Model;
using com.precisely.apis.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace com.precisely.apis.Test
{
    /// <summary>
    ///  Class for testing SchoolsNearByResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SchoolsNearByResponseTests
    {
        // TODO uncomment below to declare an instance variable for SchoolsNearByResponse
        //private SchoolsNearByResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SchoolsNearByResponse
            //instance = new SchoolsNearByResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SchoolsNearByResponse
        /// </summary>
        [Test]
        public void SchoolsNearByResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" SchoolsNearByResponse
            //Assert.IsInstanceOf(typeof(SchoolsNearByResponse), instance);
        }


        /// <summary>
        /// Test the property 'MatchedAddress'
        /// </summary>
        [Test]
        public void MatchedAddressTest()
        {
            // TODO unit test for the property 'MatchedAddress'
        }
        /// <summary>
        /// Test the property 'School'
        /// </summary>
        [Test]
        public void SchoolTest()
        {
            // TODO unit test for the property 'School'
        }
        /// <summary>
        /// Test the property 'SchoolDistrict'
        /// </summary>
        [Test]
        public void SchoolDistrictTest()
        {
            // TODO unit test for the property 'SchoolDistrict'
        }

    }

}
