/*
 * Precisely APIs
 *
 * Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
 *
 * The version of the OpenAPI document: 17.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.precisely.apis.Api;
using com.precisely.apis.Model;
using com.precisely.apis.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace com.precisely.apis.Test
{
    /// <summary>
    ///  Class for testing SpecialPurposeDistrictTax
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SpecialPurposeDistrictTaxTests
    {
        // TODO uncomment below to declare an instance variable for SpecialPurposeDistrictTax
        //private SpecialPurposeDistrictTax instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SpecialPurposeDistrictTax
            //instance = new SpecialPurposeDistrictTax();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SpecialPurposeDistrictTax
        /// </summary>
        [Test]
        public void SpecialPurposeDistrictTaxInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" SpecialPurposeDistrictTax
            //Assert.IsInstanceOf(typeof(SpecialPurposeDistrictTax), instance);
        }


        /// <summary>
        /// Test the property 'DistrictNumber'
        /// </summary>
        [Test]
        public void DistrictNumberTest()
        {
            // TODO unit test for the property 'DistrictNumber'
        }
        /// <summary>
        /// Test the property 'TaxRate'
        /// </summary>
        [Test]
        public void TaxRateTest()
        {
            // TODO unit test for the property 'TaxRate'
        }
        /// <summary>
        /// Test the property 'TaxAmount'
        /// </summary>
        [Test]
        public void TaxAmountTest()
        {
            // TODO unit test for the property 'TaxAmount'
        }

    }

}
