/*
 * Precisely APIs
 *
 * Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
 *
 * The version of the OpenAPI document: 18.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.precisely.apis.Api;
using com.precisely.apis.Model;
using com.precisely.apis.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace com.precisely.apis.Test
{
    /// <summary>
    ///  Class for testing ValidateMailingAddressInputRow
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ValidateMailingAddressInputRowTests
    {
        // TODO uncomment below to declare an instance variable for ValidateMailingAddressInputRow
        //private ValidateMailingAddressInputRow instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ValidateMailingAddressInputRow
            //instance = new ValidateMailingAddressInputRow();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ValidateMailingAddressInputRow
        /// </summary>
        [Test]
        public void ValidateMailingAddressInputRowInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ValidateMailingAddressInputRow
            //Assert.IsInstanceOf(typeof(ValidateMailingAddressInputRow), instance);
        }


        /// <summary>
        /// Test the property 'UserFields'
        /// </summary>
        [Test]
        public void UserFieldsTest()
        {
            // TODO unit test for the property 'UserFields'
        }
        /// <summary>
        /// Test the property 'AddressLine1'
        /// </summary>
        [Test]
        public void AddressLine1Test()
        {
            // TODO unit test for the property 'AddressLine1'
        }
        /// <summary>
        /// Test the property 'AddressLine2'
        /// </summary>
        [Test]
        public void AddressLine2Test()
        {
            // TODO unit test for the property 'AddressLine2'
        }
        /// <summary>
        /// Test the property 'FirmName'
        /// </summary>
        [Test]
        public void FirmNameTest()
        {
            // TODO unit test for the property 'FirmName'
        }
        /// <summary>
        /// Test the property 'City'
        /// </summary>
        [Test]
        public void CityTest()
        {
            // TODO unit test for the property 'City'
        }
        /// <summary>
        /// Test the property 'StateProvince'
        /// </summary>
        [Test]
        public void StateProvinceTest()
        {
            // TODO unit test for the property 'StateProvince'
        }
        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Test]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }
        /// <summary>
        /// Test the property 'PostalCode'
        /// </summary>
        [Test]
        public void PostalCodeTest()
        {
            // TODO unit test for the property 'PostalCode'
        }

    }

}
