/*
 * Precisely APIs
 *
 * Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
 *
 * The version of the OpenAPI document: 16.0.1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.precisely.apis.Api;
using com.precisely.apis.Model;
using com.precisely.apis.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace com.precisely.apis.Test
{
    /// <summary>
    ///  Class for testing ValidatePhoneNumberAPIRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ValidatePhoneNumberAPIRequestTests
    {
        // TODO uncomment below to declare an instance variable for ValidatePhoneNumberAPIRequest
        //private ValidatePhoneNumberAPIRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ValidatePhoneNumberAPIRequest
            //instance = new ValidatePhoneNumberAPIRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ValidatePhoneNumberAPIRequest
        /// </summary>
        [Test]
        public void ValidatePhoneNumberAPIRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ValidatePhoneNumberAPIRequest
            //Assert.IsInstanceOf(typeof(ValidatePhoneNumberAPIRequest), instance);
        }


        /// <summary>
        /// Test the property 'Input'
        /// </summary>
        [Test]
        public void InputTest()
        {
            // TODO unit test for the property 'Input'
        }

    }

}
