/*
 * Precisely APIs
 *
 * Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
 *
 * The version of the OpenAPI document: 12.0.1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = com.precisely.apis.Client.OpenAPIDateConverter;

namespace com.precisely.apis.Model
{
    /// <summary>
    /// AddressesResponse
    /// </summary>
    [DataContract]
    public partial class AddressesResponse :  IEquatable<AddressesResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AddressesResponse" /> class.
        /// </summary>
        /// <param name="page">page.</param>
        /// <param name="candidates">candidates.</param>
        /// <param name="addressList">addressList.</param>
        public AddressesResponse(string page = default(string), string candidates = default(string), List<AddressesDTO> addressList = default(List<AddressesDTO>))
        {
            this.Page = page;
            this.Candidates = candidates;
            this.AddressList = addressList;
        }

        /// <summary>
        /// Gets or Sets Page
        /// </summary>
        [DataMember(Name="page", EmitDefaultValue=false)]
        public string Page { get; set; }

        /// <summary>
        /// Gets or Sets Candidates
        /// </summary>
        [DataMember(Name="candidates", EmitDefaultValue=false)]
        public string Candidates { get; set; }

        /// <summary>
        /// Gets or Sets AddressList
        /// </summary>
        [DataMember(Name="addressList", EmitDefaultValue=false)]
        public List<AddressesDTO> AddressList { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AddressesResponse {\n");
            sb.Append("  Page: ").Append(Page).Append("\n");
            sb.Append("  Candidates: ").Append(Candidates).Append("\n");
            sb.Append("  AddressList: ").Append(AddressList).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AddressesResponse);
        }

        /// <summary>
        /// Returns true if AddressesResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of AddressesResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AddressesResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Page == input.Page ||
                    (this.Page != null &&
                    this.Page.Equals(input.Page))
                ) && 
                (
                    this.Candidates == input.Candidates ||
                    (this.Candidates != null &&
                    this.Candidates.Equals(input.Candidates))
                ) && 
                (
                    this.AddressList == input.AddressList ||
                    this.AddressList != null &&
                    input.AddressList != null &&
                    this.AddressList.SequenceEqual(input.AddressList)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Page != null)
                    hashCode = hashCode * 59 + this.Page.GetHashCode();
                if (this.Candidates != null)
                    hashCode = hashCode * 59 + this.Candidates.GetHashCode();
                if (this.AddressList != null)
                    hashCode = hashCode * 59 + this.AddressList.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
