/*
 * Precisely APIs
 *
 * Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
 *
 * The version of the OpenAPI document: 11.9.4
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = com.precisely.apis.Client.OpenAPIDateConverter;

namespace com.precisely.apis.Model
{
    /// <summary>
    /// CrimeRiskResponseList
    /// </summary>
    [DataContract]
    public partial class CrimeRiskResponseList :  IEquatable<CrimeRiskResponseList>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CrimeRiskResponseList" /> class.
        /// </summary>
        /// <param name="crimeRisk">crimeRisk.</param>
        public CrimeRiskResponseList(List<CrimeRiskResponse> crimeRisk = default(List<CrimeRiskResponse>))
        {
            this.CrimeRisk = crimeRisk;
        }

        /// <summary>
        /// Gets or Sets CrimeRisk
        /// </summary>
        [DataMember(Name="crimeRisk", EmitDefaultValue=false)]
        public List<CrimeRiskResponse> CrimeRisk { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CrimeRiskResponseList {\n");
            sb.Append("  CrimeRisk: ").Append(CrimeRisk).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CrimeRiskResponseList);
        }

        /// <summary>
        /// Returns true if CrimeRiskResponseList instances are equal
        /// </summary>
        /// <param name="input">Instance of CrimeRiskResponseList to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CrimeRiskResponseList input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.CrimeRisk == input.CrimeRisk ||
                    this.CrimeRisk != null &&
                    input.CrimeRisk != null &&
                    this.CrimeRisk.SequenceEqual(input.CrimeRisk)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.CrimeRisk != null)
                    hashCode = hashCode * 59 + this.CrimeRisk.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
