/*
 * Precisely APIs
 *
 * Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
 *
 * The version of the OpenAPI document: 11.9.3
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = com.precisely.apis.Client.OpenAPIDateConverter;

namespace com.precisely.apis.Model
{
    /// <summary>
    /// SchoolsNearByResponse
    /// </summary>
    [DataContract]
    public partial class SchoolsNearByResponse :  IEquatable<SchoolsNearByResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SchoolsNearByResponse" /> class.
        /// </summary>
        /// <param name="matchedAddress">matchedAddress.</param>
        /// <param name="school">school.</param>
        /// <param name="schoolDistrict">schoolDistrict.</param>
        public SchoolsNearByResponse(Address matchedAddress = default(Address), List<School> school = default(List<School>), SchoolDistrict schoolDistrict = default(SchoolDistrict))
        {
            this.MatchedAddress = matchedAddress;
            this.School = school;
            this.SchoolDistrict = schoolDistrict;
        }

        /// <summary>
        /// Gets or Sets MatchedAddress
        /// </summary>
        [DataMember(Name="matchedAddress", EmitDefaultValue=false)]
        public Address MatchedAddress { get; set; }

        /// <summary>
        /// Gets or Sets School
        /// </summary>
        [DataMember(Name="school", EmitDefaultValue=false)]
        public List<School> School { get; set; }

        /// <summary>
        /// Gets or Sets SchoolDistrict
        /// </summary>
        [DataMember(Name="schoolDistrict", EmitDefaultValue=false)]
        public SchoolDistrict SchoolDistrict { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SchoolsNearByResponse {\n");
            sb.Append("  MatchedAddress: ").Append(MatchedAddress).Append("\n");
            sb.Append("  School: ").Append(School).Append("\n");
            sb.Append("  SchoolDistrict: ").Append(SchoolDistrict).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SchoolsNearByResponse);
        }

        /// <summary>
        /// Returns true if SchoolsNearByResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of SchoolsNearByResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SchoolsNearByResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.MatchedAddress == input.MatchedAddress ||
                    (this.MatchedAddress != null &&
                    this.MatchedAddress.Equals(input.MatchedAddress))
                ) && 
                (
                    this.School == input.School ||
                    this.School != null &&
                    input.School != null &&
                    this.School.SequenceEqual(input.School)
                ) && 
                (
                    this.SchoolDistrict == input.SchoolDistrict ||
                    (this.SchoolDistrict != null &&
                    this.SchoolDistrict.Equals(input.SchoolDistrict))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.MatchedAddress != null)
                    hashCode = hashCode * 59 + this.MatchedAddress.GetHashCode();
                if (this.School != null)
                    hashCode = hashCode * 59 + this.School.GetHashCode();
                if (this.SchoolDistrict != null)
                    hashCode = hashCode * 59 + this.SchoolDistrict.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
